name: Demo CI

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    environment: ha_secrets_demo
    env:
      MY_NAME: Pablo
      MY_SECRET: ${{secrets.MY_SUPERSECRET}}
    steps:
    - name: Greet
      run: echo "Hola $MY_NAME desde GitHub Actions! y mi variable dice ${{vars.MY_VARIABLE}} y mi secreto es ${{secrets.MY_SUPERSECRET}} o bien $MY_SECRET"
